# Part of CAPTIVEA. Odoo 13 EE.

{
    "name": "cap_maintenance",
    "version": "13.0.1.0.3",
    "author": "captivea",
    "website": "https://www.captivea.com",
    "summary": "Maintenance module overlay for ABB Intervention project",
    "depends": ["cap_model_copy",
                "cap_settings",
                "cap_survey_report",
                "mail",
                "maintenance",
                "survey",
                "web"],
    "data": ["data/ir_sequence.xml",
             "data/ir_rule.xml",
             "data/res_company.xml",
             "data/maintenance_request_type.xml",
             "data/maintenance_stage.xml",
             "data/mail_template.xml",
             "data/survey_survey.xml",
             "data/report_paperformat.xml",
             "report/timesheet/header.xml",
             "report/timesheet/template_customer_timesheet.xml",
             "report/detailed_work_done/header.xml",
             "report/detailed_work_done/intervention_part.xml",
             "report/detailed_work_done/template_tosa.xml",
             "report/detailed_work_done/template_traction.xml",
             "report/detailed_work_done/template_puissance.xml",
             "views/attachment_picture_views.xml",
             "views/maintenance_accessories_used_views.xml",
             "views/maintenance_consignment_views.xml",
             "views/maintenance_corrective_work_done_traction_views.xml",
             "views/maintenance_detailed_report_work_done_views.xml",
             "views/maintenance_equipment_views.xml",
             "views/maintenance_flaw.xml",
             "views/maintenance_flaw_origin.xml",
             "views/maintenance_flaw_responsibility.xml",
             "views/maintenance_equipment_category_views.xml",
             "views/maintenance_equipment_group_views.xml",
             "views/maintenance_equipment_subgroup_views.xml",
             "views/maintenance_generic_list_views.xml",
             "views/maintenance_request_views.xml",
             "views/maintenance_timesheet_views.xml",
             "views/maintenance_tool_views.xml",
             "views/maintenance_travel_views.xml",
             "views/res_partner_views.xml",
             "views/res_config_settings_views.xml",
             "views/offline_starting_view.xml",
             "views/survey/survey_templates.xml",
             "data/ir_actions_act_window/maintenance_flaw.xml",
             "data/ir_actions_act_window/maintenance_flaw_origin.xml",
             "data/ir_actions_act_window/maintenance_flaw_responsibility.xml",
             "data/ir_actions_server/maintenance_request.xml",
             "data/ir_ui_menu.xml",
             "data/ir_model_access/maintenance_flaw.xml",
             "data/ir_model_access/maintenance_flaw_origin.xml",
             "data/ir_model_access/maintenance_flaw_responsibility.xml",
             "security/ir_model_access.xml",
             "data/ir_rule/maintenance_flaw.xml",
             "data/ir_rule/maintenance_flaw_origin.xml",
             "data/ir_rule/maintenance_flaw_responsibility.xml",
             "data/ir_cron/maintenance_request.xml"]
}
